name: FBK-CI

on: 
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Pull Image
      run: |
        mkdir website
        docker pull thumbsupgallery/thumbsup
    - name: Check & Change Filename
      run: |
        cd fubuki
        md5sum * | sed -e 's/\([^ ]*\) \(.*\(\..*\)\)$/mv -v \2 \1\3/' | sh || true
        cd ..
    - name: Generate Static Site Using Thumbsup
      run: docker run -t -v $GITHUB_WORKSPACE/fubuki:/input -v $GITHUB_WORKSPACE/website:/output -u $(id -u):$(id -g) thumbsupgallery/thumbsup thumbsup --input /input --output /output --title "白上吹雪表情包" --footer "Made with 🌽 by Copper / <a href=\"https://1drv.ms/u/s!Ah7V4-VT7CkBg79Na9EkE38n8Xkihg?e=WO1XgA\" target=\"_blank\">OneDrive</a> / <a href=\"https://github.com/copperion/fubuki-stickers\" target=\"_blank\">GitHub</a> / Powered by thumbsup" --google-analytics "UA-103626808-4"
    
    - name: Deploy to GitHub Branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: website # The branch the action should deploy to.
        FOLDER: 'website' # The folder the action should deploy.
        
    - name: Deploy to Coding.net Branch
      working-directory: website
      run: |
        git init
        git config user.name "GitHub Actions Bot"
        git config user.email "copperion@outlook.com"
        git add --all .
        git commit -m "Deploy from GitHub: $GITHUB_SHA"
        git push --force --quiet "https://CcoRMLeNqi:${{ secrets.CODING_TOKEN }}@e.coding.net/copperion/fubuki-stickers.git" master:master

      
